name: books
recipe: drupal9
config:
  webroot: web
services:
  appserver:
    type: php:8.1
proxy:
  appserver:
    - books.local
tooling:
  phpstan:
    service: appserver
    cmd: /app/vendor/bin/phpstan
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
