name: books
recipe: drupal9
config:
  webroot: web
services:
  node:
    type: node:14
    build:
      - npm install
proxy:
  appserver:
    - books.local
tooling:
  npm:
    service: node
  node:
    service: node
