<?php

/**
 * @file
 * Primary module hooks for Books - Activity module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\node\Entity\Node;


/**
 * Set the title of the Book as Activity Title.
 * @param Node $node
 *   The Activity being created
 */
function books_activity_node_presave($node) {
  if ($node->bundle() === 'activity') {
    $title = $node->get('field_book')->entity->get('title')->value;
    $node->set('title', $title);
  }
}
